name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v5
      with:
        fetch-depth: '0'
    - name: Use Go
      uses: actions/setup-go@v6
      with:
        go-version-file: ./go.mod
    - name: Run QA
      run: |
        make qa
